on:
  release:
    types:
      - published
  workflow_dispatch:
name: Publish OCI images

permissions: read-all

jobs:
  push-singlearch-image:
    name: Push single arch OCI images to GitHub Packages
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    steps:
      - name: Setup base image
        run: |
          if [ ${{ matrix.os }} = 'freebsd' ]; then
            echo "BASE_IMAGE=freebsd/freebsd-static:14.3" >> "$GITHUB_ENV"
          else
            ARCH=${{ matrix.arch }}
            echo "BASE_IMAGE=gcr.io/distroless/base-nossl-debian13:latest-${ARCH}" >> "$GITHUB_ENV"
          fi
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push zot container image
        uses: project-stacker/stacker-build-push-action@093acb5ad50bed0012616f46fdba73a8a7169db7 # main
        with:
          version: v1.1.0-rc3
          file: 'build/stacker.yaml'
          build-args: |
            RELEASE_TAG=${{ github.event.release.tag_name }}
            COMMIT=${{ github.event.release.tag_name }}-${{ github.sha }}
            OS=${{ matrix.os }}
            ARCH=${{ matrix.arch }}
            REPO_NAME=zot-${{ matrix.os }}-${{ matrix.arch }}
            BASE_IMAGE=${{ env.BASE_IMAGE }}
          url: docker://ghcr.io/${{ github.repository_owner }}
          tags: ${{ github.event.release.tag_name }} latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

